export const MESSAGE_TYPES = {
  AUTH_CONNECT: "AUTH_CONNECT",
  AUTH_STATUS: "AUTH_STATUS",
  AUTH_DISCONNECT: "AUTH_DISCONNECT",
  SCAN_START: "SCAN_START",
  SCAN_STOP: "SCAN_STOP",
  SCAN_PROGRESS_GET: "SCAN_PROGRESS_GET",
  SCAN_PROGRESS_EVENT: "SCAN_PROGRESS_EVENT",
  TREE_CHILDREN_GET: "TREE_CHILDREN_GET",
  TREE_COUNTS_GET: "TREE_COUNTS_GET",
  SEARCH_RUN: "SEARCH_RUN",
  STATS_GET: "STATS_GET",
  EXPORT_RUN: "EXPORT_RUN",
};
